version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pizza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

   api:
    build: .
    env_file: .env
    depends_on: [db]
    ports: ["8080:8080"]
 
